/**
 * Hardcoded Stock Universes for the Screener
 * Last Updated: 2026-06-19
 */

export const US_UNIVERSES = {
  SP100: [
    'AAPL', 'ABBV', 'ABT', 'ACN', 'ADBE', 'AIG', 'AMD', 'AMGN', 'AMT', 'AMZN',
    'AVGO', 'AXP', 'BA', 'BAC', 'BK', 'BKNG', 'BLK', 'BMY', 'BRK.B', 'C',
    'CAT', 'CHTR', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM', 'CSCO', 'CVS',
    'CVX', 'DHR', 'DIS', 'DOW', 'DUK', 'EMR', 'EXC', 'F', 'FDX', 'GD',
    'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD', 'HON', 'IBM', 'INTC',
    'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LLY', 'LMT', 'LOW', 'MA', 'MCD',
    'MDLZ', 'MDT', 'MET', 'META', 'MMM', 'MO', 'MRK', 'MS', 'MSFT', 'NEE',
    'NFLX', 'NKE', 'NVDA', 'ORCL', 'OXY', 'PEP', 'PFE', 'PG', 'PM', 'PYPL',
    'QCOM', 'RTX', 'SBUX', 'SCHW', 'SO', 'SPG', 'T', 'TGT', 'TMO', 'TMUS',
    'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB', 'V', 'VZ', 'WBA', 'WFC',
    'WMT', 'XOM'
  ],
  TECH: [
    'AAPL', 'ADBE', 'AMAT', 'AMD', 'AMZN', 'AVGO', 'CDNS', 'CRM', 'CRWD', 'CSCO',
    'FTNT', 'GOOGL', 'IBM', 'INTC', 'INTU', 'KLAC', 'META', 'MSFT', 'NOW', 'NVDA',
    'NXPI', 'PANW', 'PLTR', 'QCOM', 'ROP', 'SNOW', 'SNPS', 'TSLA', 'TXN', 'UBER'
  ],
  SP500: [
    'A', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL', 'ACN', 'ADBE', 'ADI', 'ADM',
    'ADP', 'ADSK', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM',
    'ALB', 'ALGN', 'ALL', 'ALLE', 'AMAT', 'AMCR', 'AMD', 'AME', 'AMGN', 'AMP',
    'AMT', 'AMZN', 'ANET', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APO', 'APP',
    'APTV', 'ARE', 'ARES', 'ATO', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXON', 'AXP',
    'AZO', 'BA', 'BAC', 'BALL', 'BAX', 'BBY', 'BDX', 'BEN', 'BF-B', 'BG',
    'BIIB', 'BKNG', 'BKR', 'BLDR', 'BLK', 'BMY', 'BNY', 'BR', 'BRK-B', 'BRO',
    'BSX', 'BX', 'BXP', 'C', 'CAG', 'CAH', 'CARR', 'CASY', 'CAT', 'CB',
    'CBOE', 'CBRE', 'CCI', 'CCL', 'CDNS', 'CDW', 'CEG', 'CF', 'CFG', 'CHD',
    'CHRW', 'CHTR', 'CI', 'CIEN', 'CINF', 'CL', 'CLX', 'CMCSA', 'CME', 'CMG',
    'CMI', 'CMS', 'CNC', 'CNP', 'COF', 'COHR', 'COIN', 'COO', 'COP', 'COR',
    'COST', 'CPAY', 'CPB', 'CPRT', 'CPT', 'CRH', 'CRL', 'CRM', 'CRWD', 'CSCO',
    'CSGP', 'CSX', 'CTAS', 'CTSH', 'CTVA', 'CVNA', 'CVS', 'CVX', 'D', 'DAL',
    'DASH', 'DD', 'DDOG', 'DE', 'DECK', 'DELL', 'DG', 'DGX', 'DHI', 'DHR',
    'DIS', 'DLR', 'DLTR', 'DOC', 'DOV', 'DOW', 'DPZ', 'DRI', 'DTE', 'DUK',
    'DVA', 'DVN', 'DXCM', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EG', 'EIX',
    'EL', 'ELV', 'EME', 'EMR', 'EOG', 'EQIX', 'EQR', 'EQT', 'ERIE', 'ES',
    'ESS', 'ETN', 'ETR', 'EVRG', 'EW', 'EXC', 'EXE', 'EXPD', 'EXPE', 'EXR',
    'F', 'FANG', 'FAST', 'FCX', 'FDS', 'FDX', 'FDXF', 'FE', 'FFIV', 'FICO',
    'FIS', 'FISV', 'FITB', 'FIX', 'FOX', 'FOXA', 'FRT', 'FSLR', 'FTNT', 'FTV',
    'GD', 'GDDY', 'GE', 'GEHC', 'GEN', 'GEV', 'GILD', 'GIS', 'GL', 'GLW',
    'GM', 'GNRC', 'GOOG', 'GOOGL', 'GPC', 'GPN', 'GRMN', 'GS', 'GWW', 'HAL',
    'HAS', 'HBAN', 'HCA', 'HD', 'HIG', 'HII', 'HLT', 'HON', 'HOOD', 'HPE',
    'HPQ', 'HRL', 'HSIC', 'HST', 'HSY', 'HUBB', 'HUM', 'HWM', 'IBKR', 'IBM',
    'ICE', 'IDXX', 'IEX', 'IFF', 'INCY', 'INTC', 'INTU', 'INVH', 'IP', 'IQV',
    'IR', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT', 'JBL', 'JCI',
    'JKHY', 'JNJ', 'JPM', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KKR', 'KLAC',
    'KMB', 'KMI', 'KO', 'KR', 'KVUE', 'L', 'LDOS', 'LEN', 'LH', 'LHX',
    'LII', 'LIN', 'LITE', 'LLY', 'LMT', 'LNT', 'LOW', 'LRCX', 'LULU', 'LUV',
    'LVS', 'LYB', 'LYV', 'MA', 'MAA', 'MAR', 'MAS', 'MCD', 'MCHP', 'MCK',
    'MCO', 'MDLZ', 'MDT', 'MET', 'META', 'MGM', 'MKC', 'MLM', 'MMM', 'MNST',
    'MO', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRNA', 'MRSH', 'MS', 'MSCI', 'MSFT',
    'MSI', 'MTB', 'MTD', 'MU', 'NCLH', 'NDAQ', 'NDSN', 'NEE', 'NEM', 'NFLX',
    'NI', 'NKE', 'NOC', 'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA',
    'NVR', 'NWS', 'NWSA', 'NXPI', 'O', 'ODFL', 'OKE', 'OMC', 'ON', 'ORCL',
    'ORLY', 'OTIS', 'OXY', 'PANW', 'PAYX', 'PCAR', 'PCG', 'PEG', 'PEP', 'PFE',
    'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PLD', 'PLTR', 'PM', 'PNC',
    'PNR', 'PNW', 'PODD', 'POOL', 'PPG', 'PPL', 'PRU', 'PSA', 'PSKY', 'PSX',
    'PTC', 'PWR', 'PYPL', 'Q', 'QCOM', 'RCL', 'REG', 'REGN', 'RF', 'RJF',
    'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG', 'RTX', 'RVTY', 'SATS',
    'SBAC', 'SBUX', 'SCHW', 'SHW', 'SJM', 'SLB', 'SMCI', 'SNA', 'SNDK', 'SNPS',
    'SO', 'SOLV', 'SPG', 'SPGI', 'SRE', 'STE', 'STLD', 'STT', 'STX', 'STZ',
    'SW', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TDY',
    'TECH', 'TEL', 'TER', 'TFC', 'TGT', 'TJX', 'TKO', 'TMO', 'TMUS', 'TPL',
    'TPR', 'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTD',
    'TTWO', 'TXN', 'TXT', 'TYL', 'UAL', 'UBER', 'UDR', 'UHS', 'ULTA', 'UNH',
    'UNP', 'UPS', 'URI', 'USB', 'V', 'VEEV', 'VICI', 'VLO', 'VLTO', 'VMC',
    'VRSK', 'VRSN', 'VRT', 'VRTX', 'VST', 'VTR', 'VTRS', 'VZ', 'WAB', 'WAT',
    'WBD', 'WDAY', 'WDC', 'WEC', 'WELL', 'WFC', 'WM', 'WMB', 'WMT', 'WRB',
    'WSM', 'WST', 'WTW', 'WY', 'WYNN', 'XEL', 'XOM', 'XYL', 'XYZ', 'YUM',
    'ZBH', 'ZBRA', 'ZTS'
  ],
  NASDAQ100: [
    'AAPL', 'ABNB', 'ADBE', 'ADI', 'ADP', 'ADSK', 'AEP', 'ALNY', 'AMAT', 'AMD',
    'AMGN', 'AMZN', 'APP', 'ARM', 'ASML', 'AVGO', 'AXON', 'BKNG', 'BKR', 'CCEP',
    'CDNS', 'CEG', 'CHTR', 'CMCSA', 'COST', 'CPRT', 'CRWD', 'CSCO', 'CSX', 'CTAS',
    'CTSH', 'DASH', 'DDOG', 'DXCM', 'EA', 'EXC', 'FANG', 'FAST', 'FER', 'FTNT',
    'GEHC', 'GILD', 'GOOG', 'GOOGL', 'HON', 'IDXX', 'INSM', 'INTC', 'INTU', 'ISRG',
    'KDP', 'KHC', 'KLAC', 'LIN', 'LITE', 'LRCX', 'MAR', 'MCHP', 'MDLZ', 'MELI',
    'META', 'MNST', 'MPWR', 'MRVL', 'MSFT', 'MSTR', 'MU', 'NFLX', 'NVDA', 'NXPI',
    'ODFL', 'ORLY', 'PANW', 'PAYX', 'PCAR', 'PDD', 'PEP', 'PLTR', 'PYPL', 'QCOM',
    'REGN', 'ROP', 'ROST', 'SBUX', 'SHOP', 'SNDK', 'SNPS', 'STX', 'TMUS', 'TRI',
    'TSLA', 'TTWO', 'TXN', 'VRSK', 'VRTX', 'WBD', 'WDAY', 'WDC', 'WMT', 'XEL',
    'ZS'
  ],
  SP400: [
    'AA', 'AAL', 'AAON', 'ACI', 'ACM', 'ADC', 'AEIS', 'AFG', 'AGCO', 'AHR',
    'AIT', 'ALGM', 'ALK', 'ALLY', 'ALV', 'AM', 'AMG', 'AMH', 'AMKR', 'AN',
    'ANF', 'APG', 'APPF', 'AR', 'ARMK', 'ARW', 'ARWR', 'ASB', 'ASH', 'ATI',
    'ATR', 'AVAV', 'AVNT', 'AVT', 'AVTR', 'AXTA', 'AYI', 'BAH', 'BBWI', 'BC',
    'BCO', 'BDC', 'BHF', 'BILL', 'BIO', 'BJ', 'BKH', 'BLD', 'BLKB', 'BMRN',
    'BRBR', 'BRKR', 'BROS', 'BRX', 'BSY', 'BURL', 'BWA', 'BWXT', 'BYD', 'CACI',
    'CAR', 'CART', 'CAVA', 'CBSH', 'CBT', 'CCK', 'CDP', 'CELH', 'CFR', 'CG',
    'CGNX', 'CHDN', 'CHE', 'CHH', 'CHRD', 'CHWY', 'CLF', 'CLH', 'CMC', 'CNH',
    'CNM', 'CNO', 'CNX', 'CNXC', 'COKE', 'COLB', 'COLM', 'COTY', 'CPRI', 'CR',
    'CRBG', 'CROX', 'CRS', 'CRUS', 'CSL', 'CTRE', 'CUBE', 'CUZ', 'CVLT', 'CW',
    'CXT', 'CYTK', 'DAR', 'DBX', 'DCI', 'DINO', 'DKS', 'DLB', 'DOCN', 'DOCS',
    'DOCU', 'DT', 'DTM', 'DUOL', 'DY', 'EEFT', 'EGP', 'EHC', 'ELAN', 'ELF',
    'ELS', 'ENS', 'ENSG', 'ENTG', 'EPR', 'EQH', 'ESAB', 'ESNT', 'EVR', 'EWBC',
    'EXEL', 'EXLS', 'EXP', 'EXPO', 'FAF', 'FBIN', 'FCFS', 'FCN', 'FFIN', 'FHI',
    'FHN', 'FIVE', 'FLEX', 'FLG', 'FLR', 'FLS', 'FN', 'FNB', 'FND', 'FNF',
    'FOUR', 'FR', 'FTI', 'G', 'GAP', 'GATX', 'GBCI', 'GEF', 'GGG', 'GHC',
    'GLPI', 'GME', 'GMED', 'GNTX', 'GPK', 'GT', 'GTLS', 'GWRE', 'GXO', 'H',
    'HAE', 'HALO', 'HGV', 'HIMS', 'HL', 'HLI', 'HLNE', 'HOG', 'HOMB', 'HQY',
    'HR', 'HRB', 'HWC', 'HXL', 'IBOC', 'IDA', 'IDCC', 'ILMN', 'INGR', 'IPGP',
    'IRT', 'ITT', 'JAZZ', 'JEF', 'JHG', 'JLL', 'KBH', 'KBR', 'KD', 'KEX',
    'KNF', 'KNSL', 'KNX', 'KRC', 'KRG', 'KTOS', 'LAD', 'LAMR', 'LEA', 'LECO',
    'LFUS', 'LIVN', 'LNTH', 'LOPE', 'LPX', 'LSCC', 'LSTR', 'M', 'MANH', 'MAT',
    'MEDP', 'MIDD', 'MKSI', 'MLI', 'MMS', 'MOG-A', 'MORN', 'MP', 'MSA', 'MSM',
    'MTDR', 'MTG', 'MTN', 'MTSI', 'MTZ', 'MUR', 'MUSA', 'MZTI', 'NBIX', 'NEU',
    'NFG', 'NJR', 'NLY', 'NNN', 'NOV', 'NOVT', 'NSA', 'NTNX', 'NVST', 'NVT',
    'NWE', 'NXST', 'NXT', 'NYT', 'OC', 'OGE', 'OGS', 'OHI', 'OKTA', 'OLED',
    'OLLI', 'OLN', 'ONB', 'ONTO', 'OPCH', 'ORA', 'ORI', 'OSK', 'OVV', 'OZK',
    'P', 'PAG', 'PATH', 'PB', 'PBF', 'PCTY', 'PEGA', 'PEN', 'PFGC', 'PII',
    'PINS', 'PK', 'PLNT', 'PNFP', 'POR', 'POST', 'PPC', 'PR', 'PRI', 'PSN',
    'PVH', 'QLYS', 'R', 'RBA', 'RBC', 'REXR', 'RGA', 'RGEN', 'RGLD', 'RH',
    'RLI', 'RMBS', 'RNR', 'ROIV', 'RPM', 'RRC', 'RRX', 'RS', 'RYAN', 'RYN',
    'SAIA', 'SAIC', 'SAM', 'SARO', 'SBRA', 'SCI', 'SEIC', 'SF', 'SFM', 'SGI',
    'SHC', 'SIGI', 'SIRI', 'SITM', 'SLAB', 'SLGN', 'SLM', 'SMG', 'SN', 'SNX',
    'SOLS', 'SON', 'SPXC', 'SR', 'SSB', 'SSD', 'ST', 'STAG', 'STRL', 'STWD',
    'SWX', 'SYNA', 'TCBI', 'TEX', 'THC', 'THG', 'THO', 'TKR', 'TLN', 'TMHC',
    'TNL', 'TOL', 'TREX', 'TRU', 'TTC', 'TTEK', 'TTMI', 'TWLO', 'TXNM', 'TXRH',
    'UBSI', 'UFPI', 'UGI', 'ULS', 'UMBF', 'UNM', 'USFD', 'UTHR', 'VAL', 'VC',
    'VFC', 'VICR', 'VLY', 'VMI', 'VNO', 'VNOM', 'VNT', 'VOYA', 'VVV', 'WAL',
    'WBS', 'WCC', 'WEX', 'WFRD', 'WH', 'WHR', 'WING', 'WLK', 'WMG', 'WMS',
    'WPC', 'WSO', 'WTFC', 'WTRG', 'WTS', 'WWD', 'XPO', 'XRAY', 'YETI', 'ZION'
  ],
  RUSSELL2000_TOP: [
    'AAOI', 'AAON', 'AAT', 'ABCB', 'ABG', 'ABM', 'ACAD', 'ACIW', 'ACLS', 'ADC',
    'ADPT', 'ADUS', 'AEIS', 'AEO', 'AGM', 'AGX', 'AGYS', 'AI', 'AIN', 'AIR',
    'AIT', 'AKR', 'ALG', 'ALGT', 'AMBA', 'AMC', 'AMD', 'AMKR', 'AMRC', 'ANDE',
    'ANF', 'ANIP', 'ARCB', 'ARDX', 'ARR', 'ARWR', 'ATEN', 'ATRC', 'ATRO', 'AVA',
    'AVAV', 'AWR', 'AZZ', 'B', 'BANC', 'BANF', 'BANR', 'BCC', 'BCO', 'BCPC',
    'BCRX', 'BDC', 'BELFB', 'BFAM', 'BGC', 'BHE', 'BKE', 'BKH', 'BLBD', 'BLDR',
    'BLX', 'BMI', 'BOOT', 'BOX', 'BRC', 'BTU', 'BURL', 'BUSE', 'BYD', 'CACI',
    'CAKE', 'CALM', 'CALX', 'CASH', 'CASY', 'CATY', 'CBU', 'CBZ', 'CCC', 'CCS',
    'CDE', 'CECO', 'CENTA', 'CENX', 'CHCO', 'CHDN', 'CHE', 'CHEF', 'CIEN', 'CLDX',
    'CLF', 'CMC', 'CMPR', 'CNO', 'CNOB', 'CNS', 'COHR', 'COHU', 'COKE', 'COLB',
    'COLM', 'COR', 'CORT', 'CPK', 'CPRX', 'CROX', 'CRS', 'CRUS', 'CRVL', 'CTRE',
    'CTS', 'CUBE', 'CUBI', 'CUZ', 'CVBF', 'CVCO', 'CVLT', 'CW', 'CWST', 'CWT',
    'CYTK', 'CZR', 'DAN', 'DAR', 'DBD', 'DCO', 'DCOM', 'DECK', 'DGII', 'DHT',
    'DIOD', 'DK', 'DOC', 'DORM', 'DRH', 'DV', 'DX', 'DXPE', 'DY', 'DYN',
    'ECPG', 'EE', 'EEFT', 'EFSC', 'EGP', 'EME', 'ENPH', 'ENS', 'ENSG', 'ENTG',
    'ENVA', 'EPAM', 'EPR', 'ESE', 'ESNT', 'ETSY', 'EVR', 'EVTC', 'EXEL', 'EXLS',
    'EXPO', 'EXTR', 'EZPW', 'FAF', 'FBNC', 'FBP', 'FCEL', 'FCF', 'FCFS', 'FCN',
    'FCNCA', 'FELE', 'FFBC', 'FFIN', 'FIBK', 'FICO', 'FIVE', 'FIVN', 'FIX', 'FIZZ',
    'FN', 'FNB', 'FOR', 'FORM', 'FR', 'FRME', 'FRO', 'FRPT', 'FRSH', 'FSS',
    'FUL', 'FULT', 'GABC', 'GBCI', 'GBX', 'GEF', 'GEN', 'GEO', 'GFF', 'GIII',
    'GMED', 'GNRC', 'GPI', 'GRBK', 'GRC', 'GSAT', 'GTLS', 'GTY', 'GVA', 'GWRE',
    'HAE', 'HALO', 'HASI', 'HAWK', 'HCI', 'HCSG', 'HEI', 'HEI-A', 'HIW', 'HL',
    'HLIT', 'HMN', 'HNI', 'HOMB', 'HPP', 'HQY', 'HR', 'HTH', 'HUBG', 'HUBS',
    'HURN', 'HWKN', 'IBOC', 'IBP', 'ICUI', 'IDA', 'IDCC', 'IMAX', 'IMKTA', 'INDB',
    'INSM', 'IOSP', 'IPAR', 'IRDM', 'IRT', 'ITRI', 'JOE', 'KAI', 'KALU', 'KBH',
    'KFY', 'KMPR', 'KN', 'KNX', 'KRG', 'KTOS', 'KW', 'KWR', 'LAD', 'LFUS',
    'LGND', 'LIFE', 'LION', 'LKFN', 'LMAT', 'LOPE', 'LPG', 'LPX', 'LRN', 'LSCC',
    'LTC', 'LXP', 'LZB', 'MANH', 'MATX', 'MC', 'MCRI', 'MGEE', 'MGRC', 'MHO',
    'MKSI', 'MKTX', 'MLI', 'MMS', 'MMSI', 'MNR', 'MOD', 'MOG-A', 'MOH', 'MPWR',
    'MRCY', 'MSA', 'MSTR', 'MTDR', 'MTG', 'MTH', 'MTN', 'MTRN', 'MTSI', 'MTX',
    'MTZ', 'MWA', 'MXL', 'MYRG', 'NATL', 'NBHC', 'NBIX', 'NBTB', 'NEOG', 'NHC',
    'NHI', 'NJR', 'NKTR', 'NMIH', 'NNI', 'NOG', 'NP', 'NPO', 'NSA', 'NSIT',
    'NTCT', 'NVAX', 'NWBI', 'NWE', 'NWN', 'NXST', 'NYT', 'OCUL', 'OFG', 'OGS',
    'OLED', 'OLN', 'OMCL', 'ONB', 'ORA', 'OSIS', 'OTTR', 'PARR', 'PATK', 'PAYC',
    'PB', 'PBH', 'PCTY', 'PDFS', 'PEB', 'PEGA', 'PENN', 'PFS', 'PFSI', 'PLAB',
    'PLPC', 'PLUG', 'PLUS', 'PLXS', 'PNFP', 'PODD', 'POOL', 'POR', 'POST', 'POWI',
    'POWL', 'PRI', 'PRIM', 'PRK', 'PRLB', 'PSMT', 'PTCT', 'QCRH', 'QLYS', 'QTWO',
    'RARE', 'RBCAA', 'RDN', 'RDNT', 'RELY', 'REXR', 'RGEN', 'RH', 'RHP', 'RLI',
    'RLJ', 'RMBS', 'RNG', 'RNST', 'ROG', 'RUSHA', 'SAH', 'SAIA', 'SAIC', 'SAM',
    'SANM', 'SBCF', 'SBRA', 'SEB', 'SEM', 'SF', 'SFBS', 'SFNC', 'SGI', 'SHAK',
    'SHO', 'SHOO', 'SIGI', 'SKYW', 'SLAB', 'SMCI', 'SMTC', 'SN', 'SNOW', 'SNX',
    'SPSC', 'SRCE', 'SRPT', 'SSB', 'SSD', 'STAA', 'STAG', 'STBA', 'STC', 'STE',
    'STNG', 'STRA', 'SUI', 'SUPN', 'SWX', 'SXI', 'SXT', 'SYBT', 'SYNA', 'TAL',
    'TBBK', 'TCBI', 'TCBK', 'TDW', 'TDY', 'TGTX', 'TILE', 'TLN', 'TMHC', 'TNC',
    'TNET', 'TNK', 'TOWN', 'TPC', 'TR', 'TREX', 'TRMK', 'TRNO', 'TRS', 'TTEK',
    'TTI', 'TTMI', 'TTWO', 'TXRH', 'TYL', 'UBSI', 'UCTT', 'UE', 'UEC', 'UFPI',
    'UMBF', 'UNF', 'UNFI', 'USLM', 'UTI', 'UUUU', 'VAC', 'VCYT', 'VECO', 'VG',
    'VICR', 'VIRT', 'VLY', 'VPG', 'VRNS', 'VSAT', 'VSEC', 'VSH', 'W', 'WAFD',
    'WAL', 'WBS', 'WD', 'WDFC', 'WERN', 'WIX', 'WK', 'WMK', 'WMS', 'WOR',
    'WPP', 'WSBC', 'WSFS', 'WST', 'WTFC', 'WTS', 'WTW', 'WWD', 'XHR', 'XPO'
  ],
  HEALTHCARE: [
    'A', 'ABBV', 'ABT', 'ALGN', 'AMGN', 'BAX', 'BDX', 'BIIB', 'BMY', 'BSX',
    'CAH', 'CI', 'CNC', 'COO', 'COR', 'CRL', 'CVS', 'DGX', 'DHR', 'DVA',
    'DXCM', 'ELV', 'EW', 'GEHC', 'GILD', 'HCA', 'HSIC', 'HUM', 'IDXX', 'INCY',
    'IQV', 'ISRG', 'JNJ', 'LH', 'LLY', 'MCK', 'MDT', 'MRK', 'MRNA', 'MTD',
    'PFE', 'PODD', 'REGN', 'RMD', 'RVTY', 'SOLV', 'STE', 'SYK', 'TECH', 'TMO',
    'UHS', 'UNH', 'VEEV', 'VRTX', 'VTRS', 'WAT', 'WST', 'ZBH', 'ZTS'
  ],
  ENERGY: [
    'APA', 'BKR', 'COP', 'CVX', 'DVN', 'EOG', 'EQT', 'EXE', 'FANG', 'HAL',
    'KMI', 'MPC', 'OKE', 'OXY', 'PSX', 'SLB', 'TPL', 'TRGP', 'VLO', 'WMB',
    'XOM'
  ],
  FINANCIALS: [
    'ACGL', 'AFL', 'AIG', 'AIZ', 'AJG', 'ALL', 'AMP', 'AON', 'APO', 'ARES',
    'AXP', 'BAC', 'BEN', 'BLK', 'BNY', 'BRK-B', 'BRO', 'BX', 'C', 'CB',
    'CBOE', 'CFG', 'CINF', 'CME', 'COF', 'COIN', 'CPAY', 'EG', 'ERIE', 'FDS',
    'FIS', 'FISV', 'FITB', 'GL', 'GPN', 'GS', 'HBAN', 'HIG', 'HOOD', 'IBKR',
    'ICE', 'IVZ', 'JKHY', 'JPM', 'KEY', 'KKR', 'L', 'MA', 'MCO', 'MET',
    'MRSH', 'MS', 'MSCI', 'MTB', 'NDAQ', 'NTRS', 'PFG', 'PGR', 'PNC', 'PRU',
    'PYPL', 'RF', 'RJF', 'SCHW', 'SPGI', 'STT', 'SYF', 'TFC', 'TROW', 'TRV',
    'USB', 'V', 'WFC', 'WRB', 'WTW', 'XYZ'
  ],
  CONSUMER: [
    'ABNB', 'ADM', 'AMZN', 'APTV', 'AZO', 'BBY', 'BF-B', 'BG', 'BKNG', 'CAG',
    'CASY', 'CCL', 'CHD', 'CL', 'CLX', 'CMG', 'COST', 'CPB', 'CVNA', 'DASH',
    'DECK', 'DG', 'DHI', 'DLTR', 'DPZ', 'DRI', 'EBAY', 'EL', 'EXPE', 'F',
    'GIS', 'GM', 'GPC', 'GRMN', 'HAS', 'HD', 'HLT', 'HRL', 'HSY', 'KDP',
    'KHC', 'KMB', 'KO', 'KR', 'KVUE', 'LEN', 'LOW', 'LULU', 'LVS', 'MAR',
    'MCD', 'MDLZ', 'MGM', 'MKC', 'MNST', 'MO', 'NCLH', 'NKE', 'NVR', 'ORLY',
    'PEP', 'PG', 'PHM', 'PM', 'POOL', 'RCL', 'RL', 'ROST', 'SBUX', 'SJM',
    'STZ', 'SYY', 'TAP', 'TGT', 'TJX', 'TPR', 'TSCO', 'TSLA', 'TSN', 'ULTA',
    'WMT', 'WSM', 'WYNN', 'YUM'
  ],
};

export const ID_UNIVERSES = {
  LQ45: [
    'ACES.JK', 'ADRO.JK', 'AKRA.JK', 'AMRT.JK', 'ANTM.JK', 'ARTO.JK', 'ASII.JK', 'BBCA.JK', 'BBNI.JK', 'BBRI.JK',
    'BBTN.JK', 'BMRI.JK', 'BRIS.JK', 'BRPT.JK', 'BUKA.JK', 'CPIN.JK', 'EMTK.JK', 'ESSA.JK', 'EXCL.JK', 'GGRM.JK',
    'GOTO.JK', 'HRUM.JK', 'ICBP.JK', 'INCO.JK', 'INDF.JK', 'INKP.JK', 'INTP.JK', 'ISAT.JK', 'ITMG.JK', 'KLBF.JK',
    'MAPI.JK', 'MBMA.JK', 'MDKA.JK', 'MEDC.JK', 'MTEL.JK', 'PGAS.JK', 'PGEO.JK', 'PTBA.JK', 'SIDO.JK', 'SMGR.JK',
    'SRTG.JK', 'TLKM.JK', 'TPIA.JK', 'UNTR.JK', 'UNVR.JK'
  ],
  KOMPAS100: [
    'ACES.JK', 'ADMR.JK', 'ADRO.JK', 'AGRO.JK', 'AKRA.JK', 'ALFA.JK', 'AMRT.JK', 'ANTM.JK', 'APLN.JK', 'ARTO.JK',
    'ASII.JK', 'ASRI.JK', 'AUTO.JK', 'AVIA.JK', 'BACA.JK', 'BBYB.JK', 'BBCA.JK', 'BBNI.JK', 'BBRI.JK', 'BBTN.JK',
    'BFIN.JK', 'BMRI.JK', 'BMTR.JK', 'BRIS.JK', 'BRPT.JK', 'BSDE.JK', 'BTPS.JK', 'BUKA.JK', 'CENX.JK', 'CFIN.JK',
    'CLEO.JK', 'CPIN.JK', 'CTRA.JK', 'DMMX.JK', 'DOID.JK', 'DSNG.JK', 'ELSA.JK', 'EMTK.JK', 'ENRG.JK', 'ERAA.JK',
    'ESSA.JK', 'EXCL.JK', 'FREN.JK', 'GGRM.JK', 'GOTO.JK', 'HEAL.JK', 'HMSP.JK', 'HRUM.JK', 'ICBP.JK', 'INCO.JK',
    'INDF.JK', 'INDY.JK', 'INKP.JK', 'INTP.JK', 'ISAT.JK', 'ITMG.JK', 'JPFA.JK', 'KLBF.JK', 'LSIP.JK', 'MAPI.JK',
    'MAPA.JK', 'MBMA.JK', 'MDKA.JK', 'MEDC.JK', 'MIKA.JK', 'MNCN.JK', 'MTEL.JK', 'MYOR.JK', 'NCKL.JK', 'NELY.JK',
    'PANI.JK', 'PBID.JK', 'PGAS.JK', 'PGEO.JK', 'PNBN.JK', 'PNLF.JK', 'PTBA.JK', 'PTPP.JK', 'PWON.JK', 'SCMA.JK',
    'SIDO.JK', 'SILO.JK', 'SMGR.JK', 'SMRA.JK', 'SMSM.JK', 'SRTG.JK', 'SSIA.JK', 'SSMS.JK', 'TAPG.JK', 'TBIG.JK',
    'TINS.JK', 'TKIM.JK', 'TLKM.JK', 'TOWR.JK', 'TPIA.JK', 'TRIN.JK', 'UNTR.JK', 'UNVR.JK', 'WIKA.JK', 'WSKT.JK'
  ],
  ALL: [
    "AALI.JK",
    "ABBA.JK",
    "ABDA.JK",
    "ABMM.JK",
    "ACES.JK",
    "ACST.JK",
    "ADES.JK",
    "ADHI.JK",
    "AISA.JK",
    "AKKU.JK",
    "AKPI.JK",
    "AKRA.JK",
    "AKSI.JK",
    "ALDO.JK",
    "ALKA.JK",
    "ALMI.JK",
    "ALTO.JK",
    "AMAG.JK",
    "AMFG.JK",
    "AMIN.JK",
    "AMRT.JK",
    "ANJT.JK",
    "ANTM.JK",
    "APEX.JK",
    "APIC.JK",
    "APII.JK",
    "APLI.JK",
    "APLN.JK",
    "ARGO.JK",
    "ARII.JK",
    "ARNA.JK",
    "ARTA.JK",
    "ARTI.JK",
    "ARTO.JK",
    "ASBI.JK",
    "ASDM.JK",
    "ASGR.JK",
    "ASII.JK",
    "ASJT.JK",
    "ASMI.JK",
    "ASRI.JK",
    "ASRM.JK",
    "ASSA.JK",
    "ATIC.JK",
    "AUTO.JK",
    "BABP.JK",
    "BACA.JK",
    "BAJA.JK",
    "BALI.JK",
    "BAPA.JK",
    "BATA.JK",
    "BAYU.JK",
    "BBCA.JK",
    "BBHI.JK",
    "BBKP.JK",
    "BBLD.JK",
    "BBMD.JK",
    "BBNI.JK",
    "BBRI.JK",
    "BBRM.JK",
    "BBTN.JK",
    "BBYB.JK",
    "BCAP.JK",
    "BCIC.JK",
    "BCIP.JK",
    "BDMN.JK",
    "BEKS.JK",
    "BEST.JK",
    "BFIN.JK",
    "BGTG.JK",
    "BHIT.JK",
    "BIKA.JK",
    "BIMA.JK",
    "BINA.JK",
    "BIPI.JK",
    "BIPP.JK",
    "BIRD.JK",
    "BISI.JK",
    "BJBR.JK",
    "BJTM.JK",
    "BKDP.JK",
    "BKSL.JK",
    "BKSW.JK",
    "BLTA.JK",
    "BLTZ.JK",
    "BMAS.JK",
    "BMRI.JK",
    "BMSR.JK",
    "BMTR.JK",
    "BNBA.JK",
    "BNBR.JK",
    "BNGA.JK",
    "BNII.JK",
    "BNLI.JK",
    "BOLT.JK",
    "BPFI.JK",
    "BPII.JK",
    "BRAM.JK",
    "BRMS.JK",
    "BRNA.JK",
    "BRPT.JK",
    "BSDE.JK",
    "BSIM.JK",
    "BSSR.JK",
    "BSWD.JK",
    "BTEK.JK",
    "BTEL.JK",
    "BTON.JK",
    "BTPN.JK",
    "BUDI.JK",
    "BUKK.JK",
    "BULL.JK",
    "BUMI.JK",
    "BUVA.JK",
    "BVIC.JK",
    "BWPT.JK",
    "BYAN.JK",
    "CANI.JK",
    "CASS.JK",
    "CEKA.JK",
    "CENT.JK",
    "CFIN.JK",
    "CINT.JK",
    "CITA.JK",
    "CLPI.JK",
    "CMNP.JK",
    "CMPP.JK",
    "CNKO.JK",
    "CNTX.JK",
    "COWL.JK",
    "CPIN.JK",
    "CPRO.JK",
    "CSAP.JK",
    "CTBN.JK",
    "CTRA.JK",
    "CTTH.JK",
    "DART.JK",
    "DEFI.JK",
    "DEWA.JK",
    "DGIK.JK",
    "DILD.JK",
    "DKFT.JK",
    "DLTA.JK",
    "DMAS.JK",
    "DNAR.JK",
    "DNET.JK",
    "DOID.JK",
    "DPNS.JK",
    "DSFI.JK",
    "DSNG.JK",
    "DSSA.JK",
    "DUTI.JK",
    "DVLA.JK",
    "DYAN.JK",
    "ECII.JK",
    "EKAD.JK",
    "ELSA.JK",
    "ELTY.JK",
    "EMDE.JK",
    "EMTK.JK",
    "ENRG.JK",
    "EPMT.JK",
    "ERAA.JK",
    "ERTX.JK",
    "ESSA.JK",
    "ESTI.JK",
    "ETWA.JK",
    "EXCL.JK",
    "FAST.JK",
    "FASW.JK",
    "FISH.JK",
    "FMII.JK",
    "FORU.JK",
    "FPNI.JK",
    "GAMA.JK",
    "GDST.JK",
    "GDYR.JK",
    "GEMA.JK",
    "GEMS.JK",
    "GGRM.JK",
    "GIAA.JK",
    "GJTL.JK",
    "GLOB.JK",
    "GMTD.JK",
    "GOLD.JK",
    "GOLL.JK",
    "GPRA.JK",
    "GSMF.JK",
    "GTBO.JK",
    "GWSA.JK",
    "GZCO.JK",
    "HADE.JK",
    "HDFA.JK",
    "HERO.JK",
    "HEXA.JK",
    "HITS.JK",
    "HMSP.JK",
    "HOME.JK",
    "HOTL.JK",
    "HRUM.JK",
    "IATA.JK",
    "IBFN.JK",
    "IBST.JK",
    "ICBP.JK",
    "ICON.JK",
    "IGAR.JK",
    "IIKP.JK",
    "IKAI.JK",
    "IKBI.JK",
    "IMAS.JK",
    "IMJS.JK",
    "IMPC.JK",
    "INAF.JK",
    "INAI.JK",
    "INCI.JK",
    "INCO.JK",
    "INDF.JK",
    "INDR.JK",
    "INDS.JK",
    "INDX.JK",
    "INDY.JK",
    "INKP.JK",
    "INPC.JK",
    "INPP.JK",
    "INRU.JK",
    "INTA.JK",
    "INTD.JK",
    "INTP.JK",
    "IPOL.JK",
    "ISAT.JK",
    "ISSP.JK",
    "ITMA.JK",
    "ITMG.JK",
    "JAWA.JK",
    "JECC.JK",
    "JIHD.JK",
    "JKON.JK",
    "JPFA.JK",
    "JRPT.JK",
    "JSMR.JK",
    "JSPT.JK",
    "JTPE.JK",
    "KAEF.JK",
    "KARW.JK",
    "KBLI.JK",
    "KBLM.JK",
    "KBLV.JK",
    "KBRI.JK",
    "KDSI.JK",
    "KIAS.JK",
    "KICI.JK",
    "KIJA.JK",
    "KKGI.JK",
    "KLBF.JK",
    "KOBX.JK",
    "KOIN.JK",
    "KONI.JK",
    "KOPI.JK",
    "KPIG.JK",
    "KRAS.JK",
    "KREN.JK",
    "LAPD.JK",
    "LCGP.JK",
    "LEAD.JK",
    "LINK.JK",
    "LION.JK",
    "LMAS.JK",
    "LMPI.JK",
    "LMSH.JK",
    "LPCK.JK",
    "LPGI.JK",
    "LPIN.JK",
    "LPKR.JK",
    "LPLI.JK",
    "LPPF.JK",
    "LPPS.JK",
    "LRNA.JK",
    "LSIP.JK",
    "LTLS.JK",
    "MAGP.JK",
    "MAIN.JK",
    "MAPI.JK",
    "MAYA.JK",
    "MBAP.JK",
    "MBSS.JK",
    "MBTO.JK",
    "MCOR.JK",
    "MDIA.JK",
    "MDKA.JK",
    "MDLN.JK",
    "MDRN.JK",
    "MEDC.JK",
    "MEGA.JK",
    "MERK.JK",
    "META.JK",
    "MFMI.JK",
    "MGNA.JK",
    "MICE.JK",
    "MIDI.JK",
    "MIKA.JK",
    "MIRA.JK",
    "MITI.JK",
    "MKPI.JK",
    "MLBI.JK",
    "MLIA.JK",
    "MLPL.JK",
    "MLPT.JK",
    "MMLP.JK",
    "MNCN.JK",
    "MPMX.JK",
    "MPPA.JK",
    "MRAT.JK",
    "MREI.JK",
    "MSKY.JK",
    "MTDL.JK",
    "MTFN.JK",
    "MTLA.JK",
    "MTSM.JK",
    "MYOH.JK",
    "MYOR.JK",
    "MYTX.JK",
    "NELY.JK",
    "NIKL.JK",
    "NIRO.JK",
    "NISP.JK",
    "NOBU.JK",
    "NRCA.JK",
    "OCAP.JK",
    "OKAS.JK",
    "OMRE.JK",
    "PADI.JK",
    "PALM.JK",
    "PANR.JK",
    "PANS.JK",
    "PBRX.JK",
    "PDES.JK",
    "PEGE.JK",
    "PGAS.JK",
    "PGLI.JK",
    "PICO.JK",
    "PJAA.JK",
    "PKPK.JK",
    "PLAS.JK",
    "PLIN.JK",
    "PNBN.JK",
    "PNBS.JK",
    "PNIN.JK",
    "PNLF.JK",
    "PSAB.JK",
    "PSDN.JK",
    "PSKT.JK",
    "PTBA.JK",
    "PTIS.JK",
    "PTPP.JK",
    "PTRO.JK",
    "PTSN.JK",
    "PTSP.JK",
    "PUDP.JK",
    "PWON.JK",
    "PYFA.JK",
    "RAJA.JK",
    "RALS.JK",
    "RANC.JK",
    "RBMS.JK",
    "RDTX.JK",
    "RELI.JK",
    "RICY.JK",
    "RIGS.JK",
    "RIMO.JK",
    "RODA.JK",
    "ROTI.JK",
    "RUIS.JK",
    "SAFE.JK",
    "SAME.JK",
    "SCCO.JK",
    "SCMA.JK",
    "SCPI.JK",
    "SDMU.JK",
    "SDPC.JK",
    "SDRA.JK",
    "SGRO.JK",
    "SHID.JK",
    "SIDO.JK",
    "SILO.JK",
    "SIMA.JK",
    "SIMP.JK",
    "SIPD.JK",
    "SKBM.JK",
    "SKLT.JK",
    "SKYB.JK",
    "SMAR.JK",
    "SMBR.JK",
    "SMCB.JK",
    "SMDM.JK",
    "SMDR.JK",
    "SMGR.JK",
    "SMMA.JK",
    "SMMT.JK",
    "SMRA.JK",
    "SMRU.JK",
    "SMSM.JK",
    "SOCI.JK",
    "SONA.JK",
    "SPMA.JK",
    "SQMI.JK",
    "SRAJ.JK",
    "SRIL.JK",
    "SRSN.JK",
    "SRTG.JK",
    "SSIA.JK",
    "SSMS.JK",
    "SSTM.JK",
    "STAR.JK",
    "STTP.JK",
    "SUGI.JK",
    "SULI.JK",
    "SUPR.JK",
    "TALF.JK",
    "TARA.JK",
    "TAXI.JK",
    "TBIG.JK",
    "TBLA.JK",
    "TBMS.JK",
    "TCID.JK",
    "TELE.JK",
    "TFCO.JK",
    "TGKA.JK",
    "TIFA.JK",
    "TINS.JK",
    "TIRA.JK",
    "TIRT.JK",
    "TKIM.JK",
    "TLKM.JK",
    "TMAS.JK",
    "TMPO.JK",
    "TOBA.JK",
    "TOTL.JK",
    "TOTO.JK",
    "TOWR.JK",
    "TPIA.JK",
    "TPMA.JK",
    "TRAM.JK",
    "TRIL.JK",
    "TRIM.JK",
    "TRIO.JK",
    "TRIS.JK",
    "TRST.JK",
    "TRUS.JK",
    "TSPC.JK",
    "ULTJ.JK",
    "UNIC.JK",
    "UNIT.JK",
    "UNSP.JK",
    "UNTR.JK",
    "UNVR.JK",
    "VICO.JK",
    "VINS.JK",
    "VIVA.JK",
    "VOKS.JK",
    "VRNA.JK",
    "WAPO.JK",
    "WEHA.JK",
    "WICO.JK",
    "WIIM.JK",
    "WIKA.JK",
    "WINS.JK",
    "WOMF.JK",
    "WSKT.JK",
    "WTON.JK",
    "YPAS.JK",
    "YULE.JK",
    "ZBRA.JK",
    "SHIP.JK",
    "CASA.JK",
    "DAYA.JK",
    "DPUM.JK",
    "IDPR.JK",
    "JGLE.JK",
    "KINO.JK",
    "MARI.JK",
    "MKNT.JK",
    "MTRA.JK",
    "OASA.JK",
    "POWR.JK",
    "INCF.JK",
    "WSBP.JK",
    "PBSA.JK",
    "PRDA.JK",
    "BOGA.JK",
    "BRIS.JK",
    "PORT.JK",
    "CARS.JK",
    "MINA.JK",
    "CLEO.JK",
    "TAMU.JK",
    "CSIS.JK",
    "TGRA.JK",
    "FIRE.JK",
    "TOPS.JK",
    "KMTR.JK",
    "ARMY.JK",
    "MAPB.JK",
    "WOOD.JK",
    "HRTA.JK",
    "MABA.JK",
    "HOKI.JK",
    "MPOW.JK",
    "MARK.JK",
    "NASA.JK",
    "MDKI.JK",
    "BELL.JK",
    "KIOS.JK",
    "GMFI.JK",
    "MTWI.JK",
    "ZINC.JK",
    "MCAS.JK",
    "PPRE.JK",
    "WEGE.JK",
    "PSSI.JK",
    "MORA.JK",
    "DWGL.JK",
    "PBID.JK",
    "JMAS.JK",
    "CAMP.JK",
    "IPCM.JK",
    "PCAR.JK",
    "LCKM.JK",
    "BOSS.JK",
    "HELI.JK",
    "JSKY.JK",
    "INPS.JK",
    "GHON.JK",
    "TDPM.JK",
    "DFAM.JK",
    "NICK.JK",
    "BTPS.JK",
    "SPTO.JK",
    "PRIM.JK",
    "HEAL.JK",
    "TRUK.JK",
    "PZZA.JK",
    "TUGU.JK",
    "MSIN.JK",
    "SWAT.JK",
    "TNCA.JK",
    "MAPA.JK",
    "TCPI.JK",
    "IPCC.JK",
    "RISE.JK",
    "BPTR.JK",
    "POLL.JK",
    "NFCX.JK",
    "MGRO.JK",
    "NUSA.JK",
    "FILM.JK",
    "ANDI.JK",
    "LAND.JK",
    "MOLI.JK",
    "PANI.JK",
    "DIGI.JK",
    "CITY.JK",
    "SAPX.JK",
    "SURE.JK",
    "HKMU.JK",
    "MPRO.JK",
    "DUCK.JK",
    "GOOD.JK",
    "SKRN.JK",
    "YELO.JK",
    "CAKK.JK",
    "SATU.JK",
    "SOSS.JK",
    "DEAL.JK",
    "POLA.JK",
    "DIVA.JK",
    "LUCK.JK",
    "URBN.JK",
    "SOTS.JK",
    "ZONE.JK",
    "PEHA.JK",
    "FOOD.JK",
    "BEEF.JK",
    "POLI.JK",
    "CLAY.JK",
    "NATO.JK",
    "JAYA.JK",
    "COCO.JK",
    "MTPS.JK",
    "CPRI.JK",
    "HRME.JK",
    "POSA.JK",
    "JAST.JK",
    "FITT.JK",
    "BOLA.JK",
    "CCSI.JK",
    "SFAN.JK",
    "POLU.JK",
    "KJEN.JK",
    "KAYU.JK",
    "ITIC.JK",
    "PAMG.JK",
    "IPTV.JK",
    "BLUE.JK",
    "ENVY.JK",
    "EAST.JK",
    "LIFE.JK",
    "FUJI.JK",
    "KOTA.JK",
    "INOV.JK",
    "ARKA.JK",
    "SMKL.JK",
    "HDIT.JK",
    "KEEN.JK",
    "BAPI.JK",
    "TFAS.JK",
    "GGRP.JK",
    "OPMS.JK",
    "NZIA.JK",
    "SLIS.JK",
    "PURE.JK",
    "IRRA.JK",
    "DMMX.JK",
    "SINI.JK",
    "WOWS.JK",
    "ESIP.JK",
    "TEBE.JK",
    "KEJU.JK",
    "PSGO.JK",
    "AGAR.JK",
    "IFSH.JK",
    "REAL.JK",
    "IFII.JK",
    "PMJS.JK",
    "UCID.JK",
    "GLVA.JK",
    "PGJO.JK",
    "AMAR.JK",
    "CSRA.JK",
    "INDO.JK",
    "AMOR.JK",
    "TRIN.JK",
    "DMND.JK",
    "PURA.JK",
    "PTPW.JK",
    "TAMA.JK",
    "IKAN.JK",
    "SAMF.JK",
    "SBAT.JK",
    "KBAG.JK",
    "CBMF.JK",
    "RONY.JK",
    "CSMI.JK",
    "BBSS.JK",
    "BHAT.JK",
    "CASH.JK",
    "TECH.JK",
    "EPAC.JK",
    "UANG.JK",
    "PGUN.JK",
    "SOFA.JK",
    "PPGL.JK",
    "TOYS.JK",
    "SGER.JK",
    "TRJA.JK",
    "PNGO.JK",
    "SCNP.JK",
    "BBSI.JK",
    "KMDS.JK",
    "PURI.JK",
    "SOHO.JK",
    "HOMI.JK",
    "ROCK.JK",
    "ENZO.JK",
    "PLAN.JK",
    "PTDU.JK",
    "ATAP.JK",
    "VICI.JK",
    "PMMP.JK",
    "BANK.JK",
    "WMUU.JK",
    "EDGE.JK",
    "UNIQ.JK",
    "BEBS.JK",
    "SNLK.JK",
    "ZYRX.JK",
    "LFLO.JK",
    "FIMP.JK",
    "TAPG.JK",
    "NPGF.JK",
    "LUCY.JK",
    "ADCP.JK",
    "HOPE.JK",
    "MGLV.JK",
    "TRUE.JK",
    "LABA.JK",
    "ARCI.JK",
    "IPAC.JK",
    "MASB.JK",
    "BMHS.JK",
    "FLMC.JK",
    "NICL.JK",
    "UVCR.JK",
    "BUKA.JK",
    "HAIS.JK",
    "OILS.JK",
    "GPSO.JK",
    "MCOL.JK",
    "RSGK.JK",
    "RUNS.JK",
    "SBMA.JK",
    "CMNT.JK",
    "GTSI.JK",
    "IDEA.JK",
    "KUAS.JK",
    "BOBA.JK",
    "MTEL.JK",
    "DEPO.JK",
    "BINO.JK",
    "CMRY.JK",
    "WGSH.JK",
    "TAYS.JK",
    "WMPP.JK",
    "RMKE.JK",
    "OBMD.JK",
    "AVIA.JK",
    "IPPE.JK",
    "NASI.JK",
    "BSML.JK",
    "DRMA.JK",
    "ADMR.JK",
    "SEMA.JK",
    "ASLC.JK",
    "NETV.JK",
    "BAUT.JK",
    "ENAK.JK",
    "NTBK.JK",
    "SMKM.JK",
    "STAA.JK",
    "NANO.JK",
    "BIKE.JK",
    "WIRG.JK",
    "SICO.JK",
    "GOTO.JK",
    "TLDN.JK",
    "MTMH.JK",
    "WINR.JK",
    "IBOS.JK",
    "OLIV.JK",
    "ASHA.JK",
    "SWID.JK",
    "TRGU.JK",
    "ARKO.JK",
    "CHEM.JK",
    "DEWI.JK",
    "AXIO.JK",
    "KRYA.JK",
    "HATM.JK",
    "RCCC.JK",
    "GULA.JK",
    "JARR.JK",
    "AMMS.JK",
    "RAFI.JK",
    "KKES.JK",
    "ELPI.JK",
    "EURO.JK",
    "KLIN.JK",
    "TOOL.JK",
    "BUAH.JK",
    "CRAB.JK",
    "MEDS.JK",
    "COAL.JK",
    "PRAY.JK",
    "CBUT.JK",
    "BELI.JK",
    "MKTR.JK",
    "OMED.JK",
    "BSBK.JK",
    "PDPP.JK",
    "KDTN.JK",
    "ZATA.JK",
    "NINE.JK",
    "MMIX.JK",
    "PADA.JK",
    "ISAP.JK",
    "VTNY.JK",
    "SOUL.JK",
    "ELIT.JK",
    "BEER.JK",
    "CBPE.JK",
    "SUNI.JK",
    "CBRE.JK",
    "WINE.JK",
    "BMBL.JK",
    "PEVE.JK",
    "LAJU.JK",
    "FWCT.JK",
    "NAYZ.JK",
    "IRSX.JK",
    "PACK.JK",
    "VAST.JK",
    "CHIP.JK",
    "HALO.JK",
    "KING.JK",
    "PGEO.JK",
    "FUTR.JK",
    "HILL.JK",
    "BDKR.JK",
    "PTMP.JK",
    "SAGE.JK",
    "TRON.JK",
    "CUAN.JK",
    "NSSS.JK",
    "GTRA.JK",
    "HAJJ.JK",
    "JATI.JK",
    "TYRE.JK",
    "MPXL.JK",
    "SMIL.JK",
    "KLAS.JK",
    "MAXI.JK",
    "VKTR.JK",
    "RELF.JK",
    "AMMN.JK",
    "CRSN.JK",
    "GRPM.JK",
    "WIDI.JK",
    "TGUK.JK",
    "INET.JK",
    "MAHA.JK",
    "RMKO.JK",
    "CNMA.JK",
    "FOLK.JK",
    "HBAT.JK",
    "GRIA.JK",
    "PPRI.JK",
    "ERAL.JK",
    "CYBR.JK",
    "MUTU.JK",
    "LMAX.JK",
    "HUMI.JK",
    "MSIE.JK",
    "RSCH.JK",
    "BABY.JK",
    "AEGS.JK",
    "IOTF.JK",
    "KOCI.JK",
    "PTPS.JK",
    "BREN.JK",
    "STRK.JK",
    "KOKA.JK",
    "LOPI.JK",
    "UDNG.JK",
    "RGAS.JK",
    "MSTI.JK",
    "IKPM.JK",
    "AYAM.JK",
    "SURI.JK",
    "ASLI.JK",
    "GRPH.JK",
    "SMGA.JK",
    "UNTD.JK",
    "TOSK.JK",
    "MPIX.JK",
    "ALII.JK",
    "MKAP.JK",
    "MEJA.JK",
    "LIVE.JK",
    "HYGN.JK",
    "BAIK.JK",
    "VISI.JK",
    "AREA.JK",
    "MHKI.JK",
    "ATLA.JK",
    "DATA.JK",
    "SOLA.JK",
    "BATR.JK",
    "SPRE.JK",
    "PART.JK",
    "GOLF.JK",
    "ISEA.JK",
    "BLES.JK",
    "GUNA.JK",
    "LABS.JK",
    "DOSS.JK",
    "NEST.JK",
    "PTMR.JK",
    "VERN.JK",
    "DAAZ.JK",
    "BOAT.JK",
    "NAIK.JK",
    "AADI.JK",
    "MDIY.JK",
    "KSIX.JK",
    "RATU.JK",
    "YOII.JK",
    "HGII.JK",
    "BRRC.JK",
    "DGWG.JK",
    "CBDK.JK",
    "OBAT.JK",
    "MINE.JK",
    "ASPR.JK",
    "PSAT.JK",
    "COIN.JK",
    "CDIA.JK",
    "BLOG.JK",
    "MERI.JK",
    "CHEK.JK",
    "PMUI.JK",
    "EMAS.JK",
    "PJHB.JK",
    "RLCO.JK",
    "SUPA.JK",
    "WBSA.JK",
    "KAQI.JK",
    "YUPI.JK",
    "FORE.JK",
    "MDLA.JK",
    "DKHH.JK",
    "AYLS.JK",
    "DADA.JK",
    "ASPI.JK",
    "ESTA.JK",
    "BESS.JK",
    "AMAN.JK",
    "CARE.JK",
    "PIPA.JK",
    "NCKL.JK",
    "MENN.JK",
    "AWAN.JK",
    "MBMA.JK",
    "RAAM.JK",
    "DOOH.JK",
    "CGAS.JK",
    "NICE.JK",
    "MSJA.JK",
    "SMLE.JK",
    "ACRO.JK",
    "MANG.JK",
    "WIFI.JK",
    "FAPA.JK",
    "DCII.JK",
    "KETR.JK",
    "DGNS.JK",
    "UFOE.JK",
    "ADMF.JK",
    "ADMG.JK",
    "ADRO.JK",
    "AGII.JK",
    "AGRO.JK",
    "AGRS.JK",
    "AHAP.JK",
    "AIMS.JK",
    "PNSE.JK",
    "POLY.JK",
    "POOL.JK",
    "PPRO.JK"
]
};
